# Generated by Django 6.0.6 on 2026-06-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=10, verbose_name='Грейд')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_modifier', models.FloatField(verbose_name='Коэффициент цены')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('base_market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.condition', verbose_name='Состояние')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Выкуп'), ('SELL', 'Продажа')], max_length=4, verbose_name='Тип сделки')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена сделки')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.device', verbose_name='Устройство')),
            ],
        ),
    ]
